anonymous_contact/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('community/', include('community.urls')),
    path('discussion/', include('discussion.urls')),
    path('user/', include('my_user.urls')),
    path('', include('various.urls')),
]

#это то что выводит print(admin_site.urls) (т.e здесь так то представление вроде есть(<URLPattern 'add_post/' [name='add_post']>))
'''[<URLPattern '' [name='index']>, <URLPattern 'login/' [name='login']>, <URLPattern 'logout/' [name='logout']>, <URLPattern 'password_change/' [name='password_change']>, <URLPattern 'password_change/done/' [name='password_change_done
']>, <URLPattern 'autocomplete/' [name='autocomplete']>, <URLPattern 'jsi18n/' [name='jsi18n']>, <URLPattern 'r/<int:content_type_id>/<path:object_id>/' [name='view_on_site']>, <URLResolver <URLPattern list> (None:None) 'discussion/
post/'>, <URLPattern '^(?P<app_label>discussion)/$' [name='app_list']>, <URLPattern '(?P<url>.*)$'>, <URLPattern 'add_post/' [name='add_post']>]'''

discussion/urls.py
from django.urls import path

from .views import *

app_name = 'discussion'
urlpatterns = [
    # path('post/', PostView.as_view(), name='post'),
    path('chat/', ChatsView.as_view(), name='chats'),
    path('chat/<slug:sluguser>/', ChatView.as_view(), name='chat'),
    path('group/<slug:group_id>', GroupChatView.as_view(), name='group')
]

my_user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views.views import *

app_name = 'user'
urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),

 ]

discussion/models/chat.py
import uuid

from django.db import models


class GroupMessageModel(models.Model):
    content = models.TextField()
    time_create = models.DateTimeField(auto_now_add=True)
    user_create = models.ForeignKey('my_user.User', on_delete=models.CASCADE, related_name='create_group_message')
    unseeing = models.ManyToManyField('my_user.User')
    group = models.ForeignKey('GroupChatsModel', on_delete=models.CASCADE, related_name='group_message')


# class AnonymousMessageModel(models.Model):
#     content = models.TextField()
#     time_create = models.DateTimeField(auto_now_add=True)
#     user_create = models.SlugField(unique=False)
#     chat = models.ForeignKey('AnonymousChatsModel', on_delete=models.CASCADE)
#
#     def __str__(self):
#         return self.user_create


class MessageModel(models.Model):
    content = models.TextField()
    time_create = models.DateTimeField(auto_now_add=True)
    user_create = models.ForeignKey('my_user.User', on_delete=models.CASCADE, related_name='create_chat_message')
    unseeing = models.ForeignKey('my_user.User', on_delete=models.CASCADE, null=True, related_name='unseeing_message')
    chat = models.ForeignKey('ChatsModel', on_delete=models.CASCADE, related_name='chat_message')

    def __str__(self):
        return self.user_create

    def save(self, *args, **kwargs):
        super(MessageModel, self).save(*args, **kwargs)


class ChatsModel(models.Model):
    first_user = models.ForeignKey('my_user.User', on_delete=models.CASCADE, related_name='first_author')
    second_user = models.ForeignKey('my_user.User', on_delete=models.CASCADE, related_name='second_author')
    unseeing = models.ManyToManyField('my_user.User', related_name='unseeing_chat')
    time_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_user.name[:10] + '&' + self.second_user.name[:10]


# class AnonymousChatsModel(models.Model):
#     first_user = models.SlugField()
#     second_user = models.SlugField()
#     first_nickname = models.SlugField()
#     second_nickname = models.SlugField()
#     time_create = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.first_user


class GroupChatsModel(models.Model):
    id = models.UUIDField('id', primary_key=True, default=uuid.uuid4)
    title = models.CharField(max_length=100)
    chapter = models.ForeignKey('my_user.User', on_delete=models.CASCADE, null=True, related_name='chapter_group')
    user = models.ManyToManyField('my_user.User', related_name='group_user')
    time_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

discussion/forms.py
from django import forms

from .models import *

discussion/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views import View

from my_user.models import *
from .forms import *
from .service import *
from .check_post import *


class ChatsView(LoginRequiredMixin, View):
    def get(self, request):
        chats = get_chats(request)
        all_user = get_all_user(request)
        group = get_all_group(request)
        context = {
            'my_user': request.user,
            'groups': group,
            'chats': chats,
            'all_user': all_user,
        }
        return render(request, 'discussion/Chats.html', context=context)

    def post(self, request):
        chats = get_chats(request)
        all_user = get_all_user(request)
        check_post_ChatsView(request)
        group = get_all_group(request)
        context = {
            'my_user': request.user,
            'groups': group,
            'chats': chats,
            'all_user': all_user,
        }
        return render(request, 'discussion/Chats.html', context=context)


class ChatView(LoginRequiredMixin, View):
    def get(self, request, sluguser):
        user = get_user(slug=sluguser)
        chat = get_chat(sluguser, request)
        check_post_ChatView(request, chat)
        messages = get_message(request, chat, sluguser)
        context = {
            'my_user': request.user,
            'user': user,
            'chat': chat,
            'messages': messages,
        }
        return render(request, 'discussion/Chat.html', context=context)

    def post(self, request, sluguser):
        user = get_user(slug=sluguser)
        chat = get_chat(sluguser, request)
        check_post_ChatView(request, chat)
        messages = get_message(request, chat, sluguser)
        context = {
            'my_user': request.user,
            'user': user,
            'chat': chat,
            'messages': messages,
        }
        return render(request, 'discussion/Chat.html', context=context)


class GroupChatView(View):
    def get(self, request, group_id):
        group = get_group(group_id)
        message = get_group_message(group_id, request)
        all_user = get_all_user(request)
        group_user = get_group_user(group)
        context = {
            'user_is_chapter': True if group.chapter == request.user else False,
            'group_user': group_user,
            'all_user': all_user,
            'group': group,
            'messages': message,
            'user': request.user
        }
        return render(request, 'discussion/Group.html', context=context)

    def post(self, request, group_id):
        group = get_group(group_id)
        message = get_group_message(group_id, request)
        check_post_GroupView(request, group)
        all_user = get_all_user(request)
        group_user = get_group_user(group)
        context = {
            'user_is_chapter': True if group.chapter == request.user else False,
            'group_user': group_user,
            'all_user': all_user,
            'group': group,
            'messages': message,
            'user': request.user
        }
        return render(request, 'discussion/Group.html', context=context)

discussion/templates/discussion/AnonymousChat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Анонимный чат</title>
</head>
<body>
<h1>{{Чат с :}}</h1>
{% if chat.first_user == request.user.slug %}
    <h1>{{ chat.second_nickname }}</h1>
{% else %}
    <h1>{{ chat.first_nickname }}</h1>
{% endif %}
{% for message in messages %}
<p>Отправил
{% if message.author == request.user.slug %}
{% else %}
{{ message.author }}
{% endif %}</p>
    <p>{{ message.content }}</p>
{% endfor %}
</body>
</html>

discussion/templates/discussion/Chat.html
{% extends 'base_html/base.html' %}
{% block title %}Чат с {{ user.slug }}{% endblock %}
{% block main %}
<h1>Чат с {{ user.name }} {{ user.surname }}</h1>
{% for message in messages %}
{% if messsage.create_user == my_user %}
<div class="my_message">{{ message.content }}</div>
    <form method="post">
        {% csrf_token %}
        <button type="submit" name="delete_me_message" value="{{ message.id }}">Удалить у себя</button>
    </form>
{% else %}
<div class="your_message">{{ message.content }}</div>
<form method="post">
    {% csrf_token %}
    <button type="submit" name="delete_all_message" value="{{ message.id }}">Удалить везде</button>
    <button type="submit" name="delete_me_message" value="{{ message.id }}">Удалить у себя</button>
    <button type="submit" name="start_change">Изменить сообщение</button>
</form>
{% endif %}
{% endfor %}
<form method="post">
    {% csrf_token %}
    <h1><input type="text" name="send_message">
    <button type="submit">Отправить сообщение</button></h1>
</form>
{% endblock %}

discussion/templates/discussion/Chats.html
{% extends 'base_html/base.html' %}
{% block title %}
My chats
{% endblock %}
{% block main %}
<h1>Создание чата с:</h1>
<div>{% for user in all_user %}
    <form method="post">
        {% csrf_token %}
        <button type="submit" name="create_chat" value="{{ user.slug }}">{{ user.name }} {{ user.surname }}</button>|
    </form>
    {% endfor %}
</div>
<hr>
<h1>Создание группового чата</h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="title_group">
        <button type="submit" name="create_group">Создать группу</button>|
    </form>
<hr>
<h1>Личные сообщения</h1>
{% for chat in chats %}
{% if my_user not in chat.unseeing.all %}
{% if chat.second_user == my_user  %}
<a href="{% url 'discussion:chat' chat.first_user.slug %}"><p>{{ chat.first_user.name }} {{ chat.first_user.surname }}</p></a>
{% else %}
<a href="{% url 'discussion:chat' chat.second_user.slug %}"><p>{{ chat.second_user.name }} {{ chat.second_user.surname }}</p></a>
{% endif %}
<form method="post">
    {% csrf_token %}
    <button type="submit" name="delete_chat" value="{{ chat.id }}">Удалить чат</button>
</form>
<hr>
{% endif %}
{% endfor %}
<h1>Групповые чаты</h1>
{% for group in groups %}
<a href="{% url 'discussion:group' group.id %}"><h2>{{ group.title }}</h2></a>
<form method="post">
    {% csrf_token %}
    <button type="submit" name="delete_group" value="{{ group.id }}">Покинуть группу</button>
</form>
<h2>Участники:</h2>
{% for user in group.user.all %}
{{ user.name }} {{ user.surname }}
{% endfor %}
<hr>
{% endfor %}
{% endblock %}

discussion/templates/discussion/Group.html
{% extends 'base_html/base.html' %}
{% block title %}Чат с {{ user.slug }}{% endblock %}
{% block main %}
<h1>Чат {{ group.title }}</h1>
<h1>Участники группы:</h1>
<h3>{% for user in group_user %}
{{ user.name }} {{ user.surname }}
{% endfor %}</h3>
{% if user_is_chapter %}
<hr>
<form method="post">
    {% csrf_token %}
    <select name="add_user" multiple>
        {% for user in all_user %}
        <option value="{{ user.slug }}">{{ user.name }} {{ user.surname }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Добавить пользователя">
</form>
<hr>
<form method="post">
    {% csrf_token %}
    <select name="delete_user" multiple>
        {% for user in group_user %}
        <option value="{{ user.slug }}">{{ user.name }} {{ user.surname }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Удалить пользователя">
</form>
{% endif %}
<hr>
{% for message in messages %}
{% if messsage.create_user == request.user %}
    <div class="my_message">{{ message.content }}</div>
    <form method="post">
        {% csrf_token %}
        <button type="submit" name="delete_me_message" value="{{ message.id }}">Удалить у себя</button>
    </form>
{% else %}
    <div class="your_message">{{ message.content }}</div>
    <form method="post">
        {% csrf_token %}
        <button type="submit" name="delete_all_message" value="{{ message.id }}">Удалить везде</button>
        <button type="submit" name="delete_me_message" value="{{ message.id }}">Удалить у себя</button>
        <button type="submit" name="start_change">Изменить сообщение</button>
    </form>
{% endif %}
{% endfor %}
<form method="post">
    {% csrf_token %}
    <h1><input type="text" name="send_message">
    <button type="submit">Отправить сообщение</button></h1>
</form>
{% endblock %}

discussion/templates/discussion/LookProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.username }}</title>
</head>
<body>
<h2>Информация:</h2>
<h5>Имя: {{ user.username }}</h5>
<h3>Статус: {{ user.profile.status }}</h3>
<h3>Возраст: {{ user.profile.age }}</h3>
{% if check_chat %}
<form method="post">
    {% csrf_token %}
    <button type="submit" name="create_chat">Создать чат</button>
</form>
{% else %}
<form method="post">
    {% csrf_token %}
    <button type="submit" name="redirect_chat">Перейти к чату</button>
</form>
{% endif %}
<h2>Посты {{ user.username }}</h2>
{% for post in posts %}
<h5>{{ post.title }}</h5>
<p>{{ post.content }}</p>
{% endfor %}
<form method="post">
    {% csrf_token %}
<button type="submit" name="test_redirect_chat">TEST</button>
</form>

</body>
</html>

discussion/templates/discussion/Post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'user:profile' %}">Профиль</a>
{% for post in model %}
<h1>{{ post.title }}</h1>
<p>{{ post.content }}</p>
<hr>
{% endfor %}
<h1>Здесь посты:)</h1>
</body>
</html>