anonymous_contact/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('community/', include('community.urls')),
    path('discussion/', include('discussion.urls')),
    path('user/', include('my_user.urls')),
    path('', include('various.urls')),
]

#это то что выводит print(admin_site.urls) (т.e здесь так то представление вроде есть(<URLPattern 'add_post/' [name='add_post']>))
'''[<URLPattern '' [name='index']>, <URLPattern 'login/' [name='login']>, <URLPattern 'logout/' [name='logout']>, <URLPattern 'password_change/' [name='password_change']>, <URLPattern 'password_change/done/' [name='password_change_done
']>, <URLPattern 'autocomplete/' [name='autocomplete']>, <URLPattern 'jsi18n/' [name='jsi18n']>, <URLPattern 'r/<int:content_type_id>/<path:object_id>/' [name='view_on_site']>, <URLResolver <URLPattern list> (None:None) 'discussion/
post/'>, <URLPattern '^(?P<app_label>discussion)/$' [name='app_list']>, <URLPattern '(?P<url>.*)$'>, <URLPattern 'add_post/' [name='add_post']>]'''

community/urls.py
from django.urls import path

from .views import *

app_name = 'community'
urlpatterns = [
    path('post/', PostView.as_view(), name='post'),
    path('', CommunityView.as_view(), name='community'),
    path('<slug:com_id>/', CommunityServerView.as_view(), name='community_server'),
]

discussion/urls.py
from django.urls import path

from .views import *

app_name = 'discussion'
urlpatterns = [
    # path('post/', PostView.as_view(), name='post'),
    path('chat/', ChatsView.as_view(), name='chats'),
    path('chat/<slug:sluguser>/', ChatView.as_view(), name='chat'),
    path('group/<slug:group_id>', GroupChatView.as_view(), name='group')
]

my_user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views.views import *

app_name = 'user'
urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),

 ]

community/models/community.py
from django.db import models

from discussion.models import *


class CommunityModel(models.Model):
    id = models.UUIDField(verbose_name='id', primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=200, verbose_name='name')
    info = models.OneToOneField('CommunityInfoModel', on_delete=models.CASCADE, related_name='com_main', verbose_name='info', null=True)
    subscribers = models.ManyToManyField('my_user.User', related_name='sub_com')
    moderator = models.ManyToManyField('my_user.User', related_name='mod_com')

    def save(self, *args, **kwargs):
        super(CommunityModel, self).save(*args, **kwargs)


class CommunityInfoModel(models.Model):
    chapter = models.ForeignKey('my_user.User', on_delete=models.SET_NULL, null=True, verbose_name='chapter', related_name='chapter_com')
    avatar = models.ImageField(upload_to="community/avatar/%Y/%m/%d/", null=True, verbose_name='avatar')
    topic = models.CharField(max_length=200, verbose_name='topic', null=True)
    description = models.TextField(verbose_name='description', null=True)
    chat = models.OneToOneField('discussion.GroupChatsModel', on_delete=models.CASCADE, related_name='com_info', verbose_name='com_chat', null=True)


class CommunityPostModel(models.Model):
    title = models.CharField(max_length=200, verbose_name='title')
    content = models.TextField(verbose_name='content')
    author = models.ForeignKey('my_user.User', on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to="community/post/%Y/%m/%d/", null=True, verbose_name='image')
    like = models.PositiveBigIntegerField(verbose_name='like', default=0)
    dislike = models.PositiveBigIntegerField(verbose_name='dislike', default=0)
    community = models.ForeignKey('CommunityModel', on_delete=models.CASCADE, related_name='community_post', null=True)

community/views.py
from uuid import UUID

from django.shortcuts import render
from django.views import View

from community.check_post import *
from community.service import *


# Create your views here.


class PostView(View):
    def get(self, request):
        my_user = request.user
        all_post = get_post(my_user)
        context = {
            'post': all_post
        }
        print(all_post)
        return render(request, 'community/Post.html', context=context)

    def post(self, request):
        my_user = request.user
        all_post = get_post(my_user)
        context = {
            'post': all_post
        }
        return render(request, 'community/Post.html', context=context)


class CommunityView(View):
    def get(self, request):
        all_community = get_all_community(request)
        my_community = list(chain(get_mod_community(request), get_sub_community(request)))
        context = {
            'my_community': my_community,
            'all_community': all_community,
        }
        return render(request, 'community/Community.html', context=context)

    def post(self, request):
        check_post_CommunityView(request)
        all_community = get_all_community(request)
        my_community = list(chain(get_mod_community(request), get_sub_community(request)))
        context = {
            'my_community': my_community,
            'all_community': all_community,
        }
        return render(request, 'community/Community.html', context=context)


class CommunityServerView(View):
    def get(self, request, com_id):
        com = get_community(com_id)
        post = get_community_post(com_id)
        subscribers = get_community_subscribers(request, com_id)
        moderator = get_community_moderator(request, com_id)
        my_user = request.user
        is_moderator = False if bool(my_user.mod_com.filter(id=com_id)) is False else True
        is_subscriber = False if bool(my_user.sub_com.filter(id=com_id)) is False else True
        is_chapter = False if bool(my_user.chapter_com.all()) is False else True
        friend = get_friend(request)
        context = {
            'friend': friend,
            'com': com,
            'post': post,
            'subscribers': subscribers,
            'moderator': moderator,
            'my_user': my_user,
            'is_moderator': is_moderator,
            'is_subscriber': is_subscriber,
            'is_chapter': is_chapter,
        }
        return render(request, 'community/CommunityServer.html', context=context)

    def post(self, request, com_id):
        com = get_community(com_id)
        post = get_community_post(com_id)
        subscribers = get_community_subscribers(request, com_id)
        moderator = get_community_moderator(request, com_id)
        my_user = request.user
        is_moderator = my_user.mod_com.filter(id=com_id)
        is_subscriber = my_user.sub_com.filter(id=com_id)
        is_chapter = my_user.chapter_com.filter(com_main__id=com_id)
        check_post_CommunityServerView(request, com)
        friend = get_friend(request)
        print(friend)
        context = {
            'friend': friend,
            'com': com,
            'post': post,
            'subscribers': subscribers,
            'moderator': moderator,
            'my_user': my_user,
            'is_moderator': is_moderator,
            'is_subscriber': is_subscriber,
            'is_chapter': is_chapter,
        }
        return render(request, 'community/CommunityServer.html', context=context)

community/templates/community/Community.html
{% extends 'base_html/base.html' %}
{% block title %}
Server management
{% endblock %}
{% block main %}
<h1>Все сообщества</h1>
<h3>{% for com in all_community %}
<form method="post">
    {% csrf_token %}
    <button type="submit" name="join_com" value="{{ com.id }}">{{ com.name }}</button>
</form>
{% endfor %}</h3>
<h1>Мои сообщества:</h1>
<h3>{% for com in my_community %}
<a href="{% url 'community:community_server' com.id %}">{{ com.name }}</a>|
{% endfor %}</h3>
<hr>
<h1>Создать сообщество</h1>
<form method="post">
    {% csrf_token %}
    Название:<input type="text" name="name">
    Тема:<input type="text" name="topic">
    Описание:<input type="text" name="description">
    Создавать чат?<input type="checkbox" name="chat">
    <button type="submit" name="create_community">Создать сообщество</button>
</form>
{% endblock %}

community/templates/community/CommunityServer.html
{% extends 'base_html/base.html' %}
{% block title %}
CommunityServer
{% endblock %}
{% block main %}
<h1>Настройки</h1>
{% if is_moderator %}
<form method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" value="{{ com.name }}">
    Topic: <input type="text" name="topic" value="{{ com.info.topic }}">
    Description: <input type="text" name="description" value="{{ com.info.description }}">
    <button type="submit" name="update_server">Обновить настройки</button>
</form>
<br>
<form method="post">
    {% csrf_token %}
    Title: <input type="text" name="title">
    Content: <input type="text" name="content">
    <button type="submit" name="create_post">Добавить пост</button>
</form>
{% if is_chapter %}
<form method="post">
    {% csrf_token %}
    <h3>Добавить модератора</h3><select name="add_moderator" multiple>
        {% for user in subscribers %}
        <option value="{{ user.slug }}">{{ user.name }} {{ user.surname }}</option>
        {% endfor %}
    </select>
    <h3>Удалить модератора</h3><select name="delete_moderator" multiple>
        {% for user in moderator %}
        <option value="{{ user.slug }}">{{ user.name }} {{ user.surname }}</option>
        {% endfor %}
    </select>
    <button type="submit" name="update_moderator">Обноваить список модераторов</button>
</form>
{% endif %}
{% endif %}
<hr>
{% for user in friend %}

{{ user.name }} {{ user.surname }}
{% endfor %}
<form method="post">
    {% csrf_token %}
    <select name="add_friend" multiple>
        {% for user in friend %}
        {{user.name}}
        <option value="{{ user.id }}">{{ user.name }} {{ user.surname }}</option>
        {% endfor %}
    </select>
    <button type="submit">Добавить друга в сообщество</button>
</form>
<hr>
<h1>{{ com.name }}</h1>
<h3>{{ com.info.topic }}</h3>
<p>{{ com.info.description }}</p>
{% if com.chat is not None %}
<a href="{% url 'discussion:group' com.info.chat.id %}">Перейти в чат</a>
{% endif %}
<h1>Новости</h1>
{% for p in post %}
<h2>{{ p.title }}</h2>
<p>{{ p.content }}</p>
<hr>
{% endfor %}
{% endblock %}

community/templates/community/Post.html
{% extends 'base_html/base.html' %}
{% block title %}
News
{% endblock %}
{% block main %}
<h1>Мои новости</h1>
{% for p in post %}
<h1>{{ p.title }}</h1>
<p>{{ p.content }}</p>
<i>{{ p.author }}</i>
{% endfor %}
{% endblock %}