anonymous_contact/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('community/', include('community.urls')),
    path('discussion/', include('discussion.urls')),
    path('user/', include('my_user.urls')),
    path('', include('various.urls')),
]

#это то что выводит print(admin_site.urls) (т.e здесь так то представление вроде есть(<URLPattern 'add_post/' [name='add_post']>))
'''[<URLPattern '' [name='index']>, <URLPattern 'login/' [name='login']>, <URLPattern 'logout/' [name='logout']>, <URLPattern 'password_change/' [name='password_change']>, <URLPattern 'password_change/done/' [name='password_change_done
']>, <URLPattern 'autocomplete/' [name='autocomplete']>, <URLPattern 'jsi18n/' [name='jsi18n']>, <URLPattern 'r/<int:content_type_id>/<path:object_id>/' [name='view_on_site']>, <URLResolver <URLPattern list> (None:None) 'discussion/
post/'>, <URLPattern '^(?P<app_label>discussion)/$' [name='app_list']>, <URLPattern '(?P<url>.*)$'>, <URLPattern 'add_post/' [name='add_post']>]'''

discussion/urls.py
from django.urls import path

from .views import *

app_name = 'discussion'
urlpatterns = [
    # path('post/', PostView.as_view(), name='post'),
    path('chat/', ChatsView.as_view(), name='chats'),
    path('chat/<slug:sluguser>/', ChatView.as_view(), name='chat'),
    path('group/<slug:group_id>', GroupChatView.as_view(), name='group')
]

my_user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views.views import *

app_name = 'user'
urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),

 ]

various/urls.py
from django.urls import path

from .views import *

app_name = 'various'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('search/', SearchView.as_view(), name='search'),
    path('profile/<slug:sluguser>', LookProfileView.as_view(), name='look_profile'),
    path('notifications/', NotificationsView.as_view(), name='notifications'),
    path('test/', TestView.as_view(), name='test'),
    ]

various/models/notifications.py
from django.db import models


class NotificationsModelABC(models.Model):
    class TypeNotifications(models.TextChoices):
        SEND_FRIEND = 'SF', 'SendFriend'
        SEND_COMMUNITY = 'SC', 'SendCommunity'
        SEND_GROUP = 'SG', 'SendGroup'
        ADMIN_NEWS = 'AN', 'AdminNews'

    time_create = models.DateTimeField(null=True, auto_now_add=True, verbose_name='time create')
    content = models.CharField(max_length=1000, verbose_name='content')
    type = models.CharField(max_length=200, choices=TypeNotifications.choices, verbose_name='type')
    check_notification = models.BooleanField(default=False, verbose_name='check')

    class Meta:
        abstract = True


class InviteNotificationsModel(NotificationsModelABC):
    recipient_user = models.ForeignKey('my_user.User', on_delete=models.CASCADE, related_name='recipient_invite_notifications')
    sender_user = models.ForeignKey('my_user.User', on_delete=models.CASCADE, related_name='sender_invite_notifications', null=True)
    sender_group = models.ForeignKey('discussion.GroupChatsModel', on_delete=models.CASCADE, related_name='sender_invite_notifications', null=True)
    sender_community = models.ForeignKey('community.CommunityModel', on_delete=models.CASCADE, related_name='sender_invite_notifications', null=True)
    answer = models.BooleanField(default=False, verbose_name='answer')

various/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites import requests
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View

from community.service import *
from discussion.service import *
from my_user.form import *
from my_user.models import *
from my_user.service import *
from various.check_post import *
from various.service import *


class IndexView(View):
    def get(self, request):
        return redirect(reverse_lazy('user:profile'))


class LoginView(View):
    def get(self, request):
        form = UserLoginForm()
        return render(request, 'registration/Login.html', {'form': form})

    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = get_user_model().objects.get(email=form.cleaned_data.get("email"))
            password = form.cleaned_data.get("password")
            check_pass = user.check_password(password)
            if check_pass is True:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect(reverse_lazy('user:profile'))
        return render(request, 'registration/Login.html', {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse_lazy('various:login'))


class RegisterView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'registration/Register.html', {'form': UserRegisterForm})
        else:
            return redirect(reverse_lazy('user:profile'))

    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse_lazy('user:profile'))
        return render(request, 'registration/Register.html', {'form': form})


class SearchView(View):
    def get(self, request):
        user = get_user_model().objects.get(slug=request.user.slug)
        all_user = get_my_friends(user)
        all_community = get_all_all_community()
        answer, type_answer = None, None
        context = {
            'type_answer': type_answer,
            'answer': answer,
            'all_user': all_user,
            'all_community': all_community,
        }
        return render(request, 'various/Search.html', context=context)

    def post(self, request):
        user = get_user_model().objects.get(slug=request.user.slug)
        all_user = get_my_friends(user)
        all_community = get_all_all_community()
        answer, type_answer = check_post_SearchView(request)
        print(answer, type_answer)
        context = {
            'type_answer': type_answer,
            'answer': answer,
            'all_user': all_user,
            'all_community': all_community,
        }
        return render(request, 'various/Search.html', context=context)


class LookProfileView(View):
    def get(self, request, sluguser):
        my_user = get_user_model().objects.get(slug=request.user.slug)
        user = get_user_model().objects.get(slug=sluguser)
        chat_flag = check_chat(my_user, user)
        subscriber_flag = check_subscriber(my_user, user)
        context = {
            'subscriber_flag': subscriber_flag,
            'chat_flag': chat_flag,
            'user': user,
            'my_user': my_user,
        }
        return render(request, 'various/LookProfile.html', context=context)

    def post(self, request, sluguser):
        my_user = get_user_model().objects.get(slug=request.user.slug)
        user = get_user_model().objects.get(slug=sluguser)
        check_post_LookProfileView(request, my_user, user)
        chat_flag = check_chat(my_user, user)
        subscriber_flag = check_subscriber(my_user, user)
        context = {
            'subscriber_flag': subscriber_flag,
            'chat_flag': chat_flag,
            'user': user,
            'my_user': my_user,
        }
        return render(request, 'various/LookProfile.html', context=context)


class NotificationsView(View):
    def get(self, request):
        my_user = get_user_model().objects.get(slug=request.user.slug)
        notifications = get_notifications(my_user)
        context = {
            'notifications': notifications,
        }
        return render(request, 'various/Notifications.html', context=context)

    def post(self, request):
        my_user = get_user_model().objects.get(slug=request.user.slug)
        notifications = get_notifications(my_user)
        check_post_NotificationsView(request)
        context = {
            'notifications': notifications,
        }
        return render(request, 'various/Notifications.html', context=context)


class TestView(View):
    def get(self, request):
        res = {'name': 'Pasha', 'surname': 'Komandyshko'}
        return JsonResponse(res)

various/templates/various/LookProfile.html
{% extends 'base_html/base.html' %}
{% block title %}
Search
{% endblock %}
{% block main %}
{% if subscriber_flag is False %}
<form method="post">
    {% csrf_token %}
    <button type="submit" name="send_friend">Отправить запрос в друзья</button>
</form>
{% else %}
<p>Заявка в друзья отправлена</p>
{% endif %}
{% if chat_flag is True %}
<a href="{% url 'discussion:chat' user.slug %}">Перейти к чату</a>
{% else %}
<form method="post">
    {% csrf_token %}
    <button type="submit" name="create_chat" value="{{ user.slug }}">Создать чат</button>
</form>
{% endif %}
<h2>Имя, фамилия: {{ user.name }} {{ user.surname }}</h2>
<h2>Name - {{ user.slug}}</h2>
<h2>Age - {{ user.profile.age }}</h2>
<h2>Status - {{ user.profile.status }}</h2>
<hr>
{% for f in user.profile.friends.all %}
<h2>{{ f.user.name }} {{ f.user.surname }}</h2>
{% endfor %}
<hr>
{% for post in user.profile.post.all %}
<h3>{{ post.title }}</h3>
<p>{{ post.content }}</p>
{% endfor %}
{% endblock %}

various/templates/various/Notifications.html
{% extends 'base_html/base.html' %}
{% block title %}
Search
{% endblock %}
{% block main %}
<h1>Уведомления</h1>
{% for n in notifications %}
{% if n.type == 'SF' %}
<h2>Приглашение в друзья</h2>
<p>{{ n.content }}</p>
{% if n.check_notification is False %}
<form method="post">
 {% csrf_token %}
 <input type="hidden" name="id" value="{{ n.id }}">
 <button type="submit" name="accept_friend" value="{{ n.sender_user }}">Принять приглашение</button>
 <button type="submit" name="reject_friend" value="{{ n.sender_user }}">Отклонить приглашение</button>
</form>
{% elif n.check_notification is True %}
{% if n.answer %}
<p>Вы приняли запрос</p>
{% else %}
<p>Вы отклонили запрос</p>
{% endif %}
{% endif %}
{% elif n.type == 'SC' %}
<h2>Приглашение в сообщество</h2>
<p>{{ n.content }}</p>
{% if n.check_notification is False %}
<form method="post">
 {% csrf_token %}
 <input type="hidden" name="id" value="{{ n.id }}">
 <button type="submit" name="accept_community" value="{{ n.sender_community }}">Принять приглашение</button>
 <button type="submit" name="reject_community" value="{{ n.sender_community }}">Отклонить приглашение</button>
</form>
{% elif n.check_notification is True %}
{% if n.answer %}
<p>Вы приняли запрос</p>
{% else %}
<p>Вы отклонили запрос</p>
{% endif %}
{% endif %}
{% elif n.type == 'SG' %}
<h2>Приглашение в группу</h2>
<p>{{ n.content }}</p>
{% if n.check_notification is False %}
<form method="post">
 {% csrf_token %}
 <input type="hidden" name="id" value="{{ n.id }}">
 <button type="submit" name="accept_group" value="{{ n.sender_group }}">Принять приглашение</button>
 <button type="submit" name="reject_group" value="{{ n.sender_group }}">Отклонить приглашение</button>
</form>
{% elif n.check_notification is True %}
{% if n.answer %}
<p>Вы приняли запрос</p>
{% else %}
<p>Вы отклонили запрос</p>
{% endif %}
{% endif %}
{% endif %}
<hr>
{% endfor %}
{% endblock %}

various/templates/various/Search.html
{% extends 'base_html/base.html' %}
{% block title %}
Search
{% endblock %}
{% block main %}
<h1>Поиск людей и сообществ</h1>
<form method="post">
    {% csrf_token %}
    <input type="text" name="content">
    <button type="submit" name="search_user">Поиск людей</button>
    <button type="submit" name="search_community">Поиск сообществ</button>
</form>
{% if answer is None %}
<h1>Мои друзья</h1>
{% for u in all_user %}
{% endfor %}
<h1>Мои сообщества</h1>
{% for c in all_community %}
{% endfor %}
{% else %}
{% for a in answer %}
{% if type_answer == 'community' %}

{% else %}
<a href="{% url 'various:look_profile' a.slug %}">{{ a.name }} {{ a.surname }}</a>
{% endif %}
{% endfor %}
{% endif %}
{% endblock %}